# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mean Time to Failure
email: ancker@ancker.net
description: >- # this means to ignore newlines until "baseurl:"
  Mean Time To Failure is a blog about everything from research networking, automation, python, smart home tech, cycling, and
  anything else I feel is worthy of a post. Enjoy!
twitter_username: ancker010
github_username: ancker010
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ryan Harden"
  avatar : "/assets/images/bio-photo.png"
  bio    : "Network/Security Architect, always interested in poking around and learning new things."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.ancker.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ancker010"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ancker010"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ancker010"
    - label: "Mastodon"
      icon: "fab fa-brands fa-mastodon"
      url: "https://mastodon.online/@ancker"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/ancker010"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ancker010"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ancker010"
    - label: "Mastodon"
      icon: "fab fa-brands fa-mastodon"
      url: "https://mastodon.online/@ancker"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

prose:
  ignore:
    - /\..*
    - /_config.yml
    - /atom.xml
    - /LICENSE.md
    - /_layouts
    - /_includes
    - /_data
    - Gemfile
    - .gitignore
    - CNAME
    - index.html
    - README.md
  media: 'assets/images'
  metadata:
    _pages:
      - name: "layout"
        field:
          element: "hidden"
          value: "pages"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments Enabled"
          value: false
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          alterable: true
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "posts"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "published"
        field:
          element: "hidden"
          label: "Published"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments Enabled"
          value: false
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Categories"
          placeholder: "Add Categories"
          options:
            - name: "Blog"
              value: "blog"
          alterable: true
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Python"
              value: "python"
            - name: "Networking"
              value: "networking"
          alterable: true
